class actor:
    actor_id=""
    actor_role=""
    main_works=""
    actor_name=""
    gender=""
    xingzuo=""
    birthday=""
    birtharea=""
    occupation=""
    more_name=""
    more_foreign_name=""
    imdb_id=""
    web_url=""